version: "3"
services:
  app:
    image: node:12
    volumes:
      - ./:/code
    env_file: .env
    working_dir: /code
    command: sh -c "test -d node_modules || yarn; yarn start"
    ports:
      - "8999:8080"
